Libraries in Python -> Python library is a collection of functions that allows you to perform many actions without writing your code.
ex. NumPy, matplotlib, Pandas

In [2]:
import numpy as np

# Single Dimensional Array
n1 = np.array([10,20,30,40,50])
print(n1)

# Multi Dimensional Array
n2 = np.array([[1,2,3,4],[5,6,7,8]])
print(n2)

[10 20 30 40 50]
[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print(type(n1), type(n2))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [9]:
# Initializing numpy array with zeros

n1 = np.zeros((1,2)) # First Parameter is used for defining the row size and second parameter is used for defining column size.
print(n1)

n2 = np.zeros((5,5))
print(n2)

[[0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# Initializing numpy array with same number

n1 = np.full((2,2),10) # Full method takes two parameter first one is for dimension and second one is for which number you want the same in array.
print(n1)

[[10 10]
 [10 10]]


In [13]:
# Initializing the numpy array within a range.

n1 = np.arange(10,20) # array start with 10 number and ends with 19.
print(n1)

n2 = np.arange(10,100, 10) # Third parameter is used for skip.
print(n2)

[10 11 12 13 14 15 16 17 18 19]
[10 20 30 40 50 60 70 80 90]


In [17]:
# Initializing the numpy array with random numbers

n1 = np.random.randint(1,100,5) # range 1 to 100 and 5 is used for length of array.
print(n1)

[47  9 71 18 81]


In [23]:
# Checking the shape of numpy arrays and change it.

n1 = np.array([[1,2,3],[4,5,6]])
print(n1.shape)
print(n1)

n1.shape = (1,6)
print(n1.shape)
print(n1)

(2, 3)
[[1 2 3]
 [4 5 6]]
(1, 6)
[[1 2 3 4 5 6]]


In [33]:
# Joining numpy arrays

n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

n3 = np.vstack((n1,n2))
print(n3)

n4 = np.hstack((n1,n2))
print(n4)

n5 = np.column_stack((n1,n2))
print(n5)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [36]:
#Numpy Intersection and Difference

n1 = np.arange(10,17)
n2 = np.arange(14,20)

n3 = np.intersect1d(n1,n2)
print(n3)

n4 = np.setdiff1d(n1,n2)
print(n4)

n5 = np.setdiff1d(n2,n1)
print(n5)

[14 15 16]
[10 11 12 13]
[17 18 19]


In [41]:
# Addition of numpy arrays

n1 = np.array([10,20,30])
n2 = np.array([30,40,50])

print(np.sum([n1,n2]))

print(np.sum([n1,n2], axis=0)) # 0 is used for column 
print(np.sum([n1,n2], axis=1)) # 1 is used for row.

180
[40 60 80]
[ 60 120]


In [42]:
# Basic Mathematics

n1 = np.array([10,20,30])
n1 += 1
print(n1)

[11 21 31]


In [43]:
n1 = np.array([10,20,30])
n1 *= 2
print(n1)

[20 40 60]


In [44]:
n1 = np.array([10,20,30])
n1 -= 1
print(n1)

[ 9 19 29]


In [46]:
n1 = np.array([10,20,30])
n1 = n1 / 5
print(n1)

[2. 4. 6.]


In [52]:
# Numpy math functions

n1 = np.arange(10,70,10)
print(n1, np.mean(n1)) # mean

n2 = np.random.randint(1,100,6)
print(n2, np.median(n2)) # median

n3 = np.random.randint(1,100,6)
print(n3, np.std(n3)) # standard deviation

[10 20 30 40 50 60] 35.0
[39 95 49 40 83 37] 44.5
[84 36  5 12 51 93] 33.19345651714439


In [53]:
# Saving and Loading numpy array

n1 = np.array([1,23,4,4,56,7,7])
np.save('ex_1',n1)

In [56]:
n2 = np.load('ex_1.npy')
print(n2)

[ 1 23  4  4 56  7  7]
